spring.application.name=inventory-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5441/inventory
spring.datasource.username=inventory
spring.datasource.password=inventory

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.consumer.group-id=inventory-service
spring.kafka.consumer.auto-offset-reset=earliest
