spring.application.name=order-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5440/orders
spring.datasource.username=orders
spring.datasource.password=orders

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
